name: deploy

on:
  push:
    branches:
      - develop
      - main
  # workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 144.31.68.92
          port: 22
          username: ilya
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: |
            cd www/api && \
            git pull origin main && \
            # npm install && \
            # npm run build && \
            php artisan config:clear && \
            php artisan view:clear && \
            php artisan route:clear && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan view:cache && \
            sudo service php8.3-fpm reload
